mobile=7800515151
name=Aksh
email=aks.01@yahoo.com
testname=healthians gym male package
number_of_members=
url=https://webd003.healthians.co.in
city=gurgaon
awsdburl=jdbc:mysql://devdb001.crljpighpbvc.ap-south-1.rds.amazonaws.com:3306/d10
dburl=jdbc:mysql://gateway.echl.in:10301/d10
dbuser=akshay_mankar
dbpassword=uLew5RIaxrvbsF36yL6oIpvD